name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20   # bez cache — brak lockfile’a

      - name: Build
        working-directory: frontend
        env:
          # Ustaw w repo → Settings → Variables → Actions → API_BASE_URL
          VITE_API_BASE_URL: ${{ vars.API_BASE_URL }}
          # Wymusza prawidłowe base dla GitHub Pages w vite.config.ts
          GITHUB_PAGES: 'true'
        run: |
          npm install --no-audit --no-fund
          npm run build

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
